import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import ActiveSectionContextProvider from "@/context/active-section-context";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.className} flex justify-center bg-blue-200 bg-circuit-board`}
      >
        <ActiveSectionContextProvider>
          <div className="mx-36 my-32 flex flex-col items-center rounded-2xl bg-white px-40 py-4">
            <Header />
            {children}
            <Footer />
          </div>
        </ActiveSectionContextProvider>
      </body>
    </html>
  );
}
