import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import ActiveSectionContextProvider from "@/context/active-section-context";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.className} flex justify-center bg-blue-200 bg-circuit-board`}
      >
        <ActiveSectionContextProvider>
          <div className="flex w-full flex-col items-center bg-white pb-4 md:py-4 lg:my-16 lg:w-[initial] lg:rounded-2xl lg:px-16 xl:my-32 xl:px-20 2xl:my-40 2xl:px-40">
            <Header />
            {children}
            <Footer />
          </div>
        </ActiveSectionContextProvider>
      </body>
    </html>
  );
}
